# backend = "glx";
# vsync = true;
# 
# # rendimiento
# use-damage = true;
# unredir-if-possible = true;
# 
# # sombras OFF (ahorra recursos)
# shadow = false;
# 
# # transparencias OFF
# inactive-opacity = 1.0;
# active-opacity = 1.0;
# frame-opacity = 1.0;
# 
# # animaciones OFF
# fading = false;
# 
# # blur OFF (MUY importante)
# blur-method = "none";
# 
# # esquinas (opcional, pero barato)
# corner-radius = 0;
# 
# # evita problemas con fullscreen/video
# unredir-if-possible-exclude = [
#   "class_g = 'Firefox'",
#   "class_g = 'Chromium'"
# ];

#################################
# Shadows (opcional)
#################################
shadow = false;

#################################
# Fading (desactivado = más rápido)
#################################
fading = false;

#################################
# General
#################################
backend = "xrender";
vsync = true;
use-damage = true;
